spring:
  datasource:
    driver-class-name : com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jrtp
    username: root
    password: Sivaji@1997 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

spring:
  mail:
    host: smtp.gmail.com
    username: sivajik6300@gmail.com
    password: 
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    

