spring:
  datasource:
    driver-class-name : com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jrtp
    username: root
    password: Sivaji@1997 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
